// frameworks-comparison-angular/src/app/layouts/auth-layout/auth-layout.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-auth-layout',
  templateUrl: './auth-layout.component.html',
  styleUrls: [
    './auth-layout.component.scss',
    '../../../assets/scss/global.scss',
  ],
})
export class AuthLayoutComponent {}




<div class="App">
      <div className="auth-layout">
        <router-outlet></router-outlet>
      </div>
      <div className="auth-image">
        <img src="../../../assets//images/auth-image.png" alt="logo" />
      </div>
    </div>

// frameworks-comparison-react/src/layouts/auth-layout/AuthLayout.tsx
import { Outlet, Navigate } from "react-router-dom";
import { useSelector } from "react-redux";
import "./AuthLayout.scss";
import AuthImage from "../../assets/images/auth-image.png";

const AuthLayout = () => {
  const { isLoggedIn } = useSelector((state: any) => {
    return state.auth;
  });

  return (
    <>
      {isLoggedIn ? (
        <Navigate to="/home" />
      ) : (
        <>
          <div className="auth-layout">
            <Outlet />
          </div>
          <div className="auth-image">
            <img src={AuthImage} alt="logo" />
          </div>
        </>
      )}
    </>
  );
};

export default AuthLayout;
