// frameworks-comparison-angular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { PostService } from '../../../services/postService';
import { IPost } from '../../../types/index';
import { BehaviorSubject } from 'rxjs';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnInit {
  posts: IPost[] = [];
  searchQuery: FormControl = new FormControl('');

  isPostsLoading: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(true);

  constructor(private postService: PostService) {}

  ngOnInit(): void {
    this.getPosts();
  }

  getPosts(): void {
    this.isPostsLoading.next(true);
    this.postService.getPosts().subscribe(
      (response: any) => {
        this.posts = response.posts.reverse();
        this.isPostsLoading.next(false);
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
  }

  searchPosts(): void {
    console.log('searchQuery', this.searchQuery.value);

    this.isPostsLoading.next(true);
    if (this.searchQuery.value.length > 0) {
      this.postService.searchPosts(this.searchQuery.value).subscribe(
        (response: any) => {
          this.posts = response.posts;
          this.isPostsLoading.next(false);
        },
        (error: any) => {
          this.posts = [];
          console.error('Error fetching posts:', error);
        }
      );
    } else {
      this.getPosts();
    }
  }
}

<div class="right-container">
    <div class="title-wrapper">
        <img src="../../../assets/icons/home-black.svg" alt="Saved icon">
      <h4>Home Page</h4>
    </div>
    <app-search placeholder="Search" (onSearch)="searchPosts()" formControlName="searchQuery"></app-search>
    <ng-container *ngIf="isPostsLoading | async; else postsList">
      <app-loader></app-loader>
    </ng-container>
    <ng-template #postsList>
      <div>
        <app-post-card *ngFor="let post of posts; let i = index" [post]="post" (getPosts)="getPosts()"></app-post-card>
      </div>
    </ng-template>
  </div>

// frameworks-comparison-vue/src/pages/Home.vue
<script lang="ts">
import HomeIcon from "../assets/icons/home-black.svg";
import Search from "@/components/Search.vue";
import Loader from "@/components/Loader.vue";
import PostCard from "../components/PostCard.vue";
import PostService from "../services/postService";
import { IPost } from "../types/index";

export default {
  data() {
    return {
      posts: [] as IPost[],
      searchQuery: "",
      isPostsLoading: true as boolean,
    };
  },
  components: {
    Search,
    PostCard,
    Loader,
  },
  methods: {
    handleSearchPosts() {
      this.isPostsLoading = true;

      if (this.searchQuery.length > 0) {
        PostService.searchPosts(this.searchQuery)
          .then((response) => {
            this.posts = response.posts;
            this.isPostsLoading = false;
          })
          .catch((error) => {
            this.posts = [];
            console.error("Error fetching posts:", error);
          });
      } else {
        this.handleGetPosts();
      }
    },
    handleGetPosts() {
      this.isPostsLoading = true;
      PostService.getPosts()
        .then((response) => {
          this.posts = response.posts.reverse();
          this.isPostsLoading = false;
        })
        .catch((error) => {
          console.error("Error fetching posts:", error);
        });
    },
    handleSearchQueryChange(e: any) {
      this.searchQuery = e.target.value;
    },
  },
  computed: {
    HomeIcon() {
      return HomeIcon;
    },
  },
  mounted() {
    this.handleGetPosts();
  },
};
</script>

<template>
  <div class="right-container">
    <div class="title-wrapper">
      <img :src="HomeIcon" alt="home" class="title-wrapper-img" />
      <h4>Home Page</h4>
    </div>
    <Search placeholder="Search" @search="handleSearchPosts" :onChange="handleSearchQueryChange" :value="searchQuery" />
    <div v-if="isPostsLoading && !posts">
      <Loader />
    </div>
    <div v-else>
      <div v-for="(post, postId) in posts" :key="postId">
        <PostCard :post="post" :getPosts="handleGetPosts" />
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss"></style>
