// frameworks-comparison-react/src/pages/PostDetails/PostDetails.tsx
import React, { useEffect, useState } from "react";
import "./PostDetails.scss";
import PostCard from "../../components/PostCard/PostCard";
import PostService from "../../services/postService";
import { IPost } from "../../types";
import { ReactComponent as BackIcon } from "../../assets/icons/back.svg";
import { useParams } from "react-router-dom";
import Loader from "../../components/Loader/Loader";
import { useNavigate } from "react-router-dom";

const PostDetails = () => {
  const navigate = useNavigate();
  const [post, setPost] = useState<IPost[]>();
  const [isPostLoading, setIsPostLoading] = useState<boolean>(true);
  const { id: postId } = useParams();

  const handleGetPost = () => {
    if (postId) {
      PostService.getPostById(postId)
        .then((response: any) => {
          setPost(response.post);
          setIsPostLoading(false);
        })
        .catch((error: any) => {
          console.error("Error fetching posts:", error);
        });
    }
  };

  useEffect(() => {
    handleGetPost();
  }, []);

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <BackIcon onClick={() => navigate(-1)} style={{ cursor: "pointer" }} />
        <h4>Back</h4>
      </div>
      {isPostLoading && !post ? <Loader /> : <PostCard post={post} getPosts={handleGetPost} />}
    </div>
  );
};

export default PostDetails;

// frameworks-comparison-vue/src/pages/PostDetails.vue
<script>
import PostCard from "@/components/PostCard.vue";
import PostService from "@/services/postService";
import Loader from "@/components/Loader.vue";
import BackIcon from "@/assets/icons/back.svg";

export default {
  components: {
    PostCard,
    Loader,
  },
  data() {
    return {
      postId: null,
      post: null,
      isPostLoading: true,
      BackIcon: BackIcon,
    };
  },
  methods: {
    handleGetPost() {
      if (this.postId) {
        PostService.getPostById(this.postId)
          .then((response) => {
            this.post = response.post;
            this.isPostLoading = false;
          })
          .catch((error) => {
            console.error("Error fetching posts:", error);
          });
      }
    },
    navigateBack() {
      this.$router.go(-1);
    },
  },
  mounted() {
    this.postId = this.$route.params.id;
    this.handleGetPost();
  },
};
</script>

<template>
  <div class="right-container">
    <div class="title-wrapper">
      <img :src="BackIcon" alt="back" style="cursor: pointer" @click="navigateBack" class="title-wrapper-img" />
      <h4>Back</h4>
    </div>
    <div v-if="isPostLoading && !post">
      <Loader />
    </div>
    <div v-else>
      <PostCard :post="post" :getPosts="handleGetPost" />
    </div>
  </div>
</template>
