// frameworks-comparison-react/src/pages/Profile/Profile.tsx
import React, { useState, useEffect } from "react";
import "./Profile.scss";
import { useNavigate, useParams } from "react-router-dom";
import Button from "../../components/button/Button";
import { IPost, IUser } from "../../types";
import { useSelector } from "react-redux";
import UserService from "../../services/userService";
import { ReactComponent as LikeImg } from "../../assets/icons/like.svg";
import { ReactComponent as PostImg } from "../../assets/icons/posts.svg";

import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";

interface PostsListProps {
  posts: IPost[] | undefined;
  option: "posts" | "liked-posts";
}

const Profile = () => {
  const navigate = useNavigate();
  const [selectedTab, setSelectedTab] = useState<"posts" | "liked-posts">("posts");
  const { id: userId } = useParams();
  const { user } = useSelector((state: any) => state.auth);

  const [activeUser, setActiveUser] = useState<IUser>();

  // const [userPosts, setUserPosts] = useState<IPost[] | undefined>();
  // const [userLikedPosts, setUserLikedPosts] = useState<IPost[] | undefined>();

  useEffect(() => {
    if (userId) {
      UserService.getUserById(userId)
        .then((response) => {
          setActiveUser(response.user);
        })
        .catch((error: any) => {
          console.error("Error fetching users:", error);
        });
    }
  }, []);

  const handleTabChange = (tab: "posts" | "liked-posts") => {
    setSelectedTab(tab);
  };

  const handleEditProfile = () => {
    if (activeUser) {
      navigate(`/update-profile/${activeUser._id}`);
    }
  };

  return (
    <div className="right-container">
      <div className="user-profile">
        <div className="profile-header">
          <img src={activeUser?.imageUrl ? activeUser?.imageUrl : ProfilePlaceholder} alt="profile" className="profile-img" />
          <div className="profile-info">
            <p className="profile-username">{activeUser?.userName}</p>
            <p className="profile-bio">{activeUser?.bio}</p>
          </div>

          {user.userId === userId ? <Button text="Edit Profile" onClick={handleEditProfile} /> : null}
        </div>

        {/* <div className="posts-tabs">
          <div onClick={() => handleTabChange("posts")} className={selectedTab === "posts" ? "tab active" : "tab"}>
            <PostImg />
            <p>Posts</p>
          </div>
          <div onClick={() => handleTabChange("liked-posts")} className={selectedTab === "liked-posts" ? "tab active" : "tab"}>
            <LikeImg />
            <p>Liked Posts</p>
          </div>
        </div>
        <PostsList posts={selectedTab === "posts" ? userPosts : userLikedPosts} option={selectedTab} /> */}
      </div>
    </div>
  );
};

const PostsList = ({ posts, option }: PostsListProps) => {
  return (
    <>
      {posts && posts.length > 0 ? (
        posts.map((post) => {
          return <>{post.caption}</>;
        })
      ) : (
        <p style={{ display: "flex", justifyContent: "center" }}>No {option === "liked-posts" ? "liked " : ""}posts</p>
      )}
    </>
  );
};

export default Profile;

// frameworks-comparison-vue/src/pages/Profile.vue
<script>
import Button from "../components/Button.vue";
import ProfilePlaceholder from "../assets/icons/profile-placeholder.svg";
import UserService from "../services/userService";
import { useAuthStore } from "@/stores/useAuthStore";

export default {
  components: {
    Button,
  },
  data() {
    return {
      activeUser: null,
      authStore: useAuthStore(),
    };
  },
  computed: {
    userId() {
      return this.$route.params.id;
    },
    user() {
      return this.authStore.user;
    },
    ProfilePlaceholder() {
      return ProfilePlaceholder;
    },
  },
  mounted() {
    this.fetchUser();
  },
  methods: {
    fetchUser() {
      const userId = this.userId;
      if (userId) {
        UserService.getUserById(userId)
          .then((response) => {
            this.activeUser = response.user;
          })
          .catch((error) => {
            console.error("Error fetching users:", error);
          });
      }
    },
    handleEditProfile() {
      if (this.activeUser) {
        this.$router.push(`/update-profile/${this.activeUser._id}`);
      }
    },
  },
};
</script>

<template>
  <div class="right-container">
    <div class="user-profile">
      <div class="profile-header">
        <img :src="activeUser?.imageUrl ? activeUser.imageUrl : ProfilePlaceholder" alt="profile" class="profile-img" />
        <div class="profile-info">
          <p class="profile-username">{{ activeUser ? activeUser.userName : "" }}</p>
          <p class="profile-bio">{{ activeUser ? activeUser.bio : "" }}</p>
        </div>
        <Button v-if="user.userId === userId" text="Edit Profile" @click="handleEditProfile" />
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import "../assets/scss/variables.scss";

.user-profile {
  display: flex;
  flex-direction: column;
  gap: 2.5rem;
  .profile-header {
    display: flex;
    gap: 1.75rem;
    .profile-img {
      width: 9rem;
      height: 9rem;
      border-radius: 100%;
    }
    .profile-info {
      width: 100%;
      display: flex;
      flex-direction: column;
      gap: 10px;
      .profile-username {
        font-size: 36px;
        font-weight: bold;
      }
    }
  }
  .posts-tabs {
    width: 100%;
    display: flex;
    .tab {
      display: flex;
      width: 12rem;
      gap: 0.75rem;
      padding-top: 1rem;
      padding-bottom: 1rem;
      align-items: center;
      justify-content: center;
      transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter,
        backdrop-filter, -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
      background-color: $primary-100;
      cursor: pointer;
      border: 1px solid $primary-500;
      background-color: transparent;
      color: $primary-500;
    }
    .tab:first-child {
      border-top-left-radius: 0.5rem;
      border-bottom-left-radius: 0.5rem;
    }
    .tab:last-child {
      border-top-right-radius: 0.5rem;
      border-bottom-right-radius: 0.5rem;
    }

    .tab:first-child {
      border-top-left-radius: 0.5rem;
      border-bottom-left-radius: 0.5rem;

      &.active {
        background-color: $primary-500;
        color: $white;
        svg {
          path {
            stroke: $white;
          }
          circle {
            stroke: $white;
          }
        }
      }
    }
    .tab:last-child {
      border-top-right-radius: 0.5rem;
      border-bottom-right-radius: 0.5rem;
      &.active {
        background-color: $primary-500;
        color: $white;
        svg {
          path {
            fill: $white;
          }
        }
      }
    }
  }
}
</style>
