// frameworks-comparison-react/src/pages/Saved/Saved.tsx
import { useEffect, useState } from "react";
import { ReactComponent as SavedIcon } from "../../assets/icons/bookmark-black.svg";
import Loader from "../../components/loader/Loader";
import { IPost } from "../../types";
import PostService from "../../services/postService";
import { useSelector } from "react-redux";
import GridPostList from "../../components/grid-post-list/GridPostList";

const Saved = () => {
  const [isPostsLoading, setIsPostsLoading] = useState<boolean>(false);
  const [savedPosts, setSavedPosts] = useState<IPost[]>([]);

  const { user } = useSelector((state: any) => {
    return state.auth;
  });

  useEffect(() => {
    setIsPostsLoading(true);
    PostService.getLikedPosts(user.userId)
      .then((response) => {
        setSavedPosts(response.likedPosts);
        setIsPostsLoading(false);
      })
      .catch((error: any) => {
        console.error("Error fetching posts:", error);
      });
  }, [user.userId]);

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <SavedIcon />
        <h4>Saved</h4>
      </div>
      {isPostsLoading && !savedPosts ? <Loader /> : <GridPostList posts={savedPosts} />}
    </div>
  );
};

export default Saved;

// frameworks-comparison-vue/src/pages/Saved.vue
<script>
import SavedIcon from "../assets/icons/bookmark-black.svg";
import Loader from "../components/Loader.vue";
import GridPostList from "../components/GridPostList.vue";
import PostService from "../services/postService";
import { useAuthStore } from "@/stores/useAuthStore";

export default {
  components: {
    Loader,
    GridPostList,
  },
  data() {
    return {
      isPostsLoading: false,
      savedPosts: [],
      authStore: useAuthStore(),
    };
  },
  created() {
    this.fetchSavedPosts();
  },
  methods: {
    fetchSavedPosts() {
      this.isPostsLoading = true;
      const user = this.authStore.user;
      PostService.getLikedPosts(user.userId)
        .then((response) => {
          this.savedPosts = response.likedPosts;
          this.isPostsLoading = false;
        })
        .catch((error) => {
          console.error("Error fetching posts:", error);
        });
    },
  },
  computed: {
    SavedIcon() {
      return SavedIcon;
    },
  },
};
</script>

<template>
  <div class="right-container">
    <div class="title-wrapper">
      <img :src="SavedIcon" alt="saved" class="title-wrapper-img" />
      <h4>Saved</h4>
    </div>
    <template v-if="isPostsLoading && !savedPosts">
      <Loader />
    </template>
    <template v-else>
      <GridPostList :posts="savedPosts" />
    </template>
  </div>
</template>
