// frameworks-comparison-react/src/pages/UpdateProfile/UpdateProfile.tsx
import React, { useState, ChangeEvent, useRef } from "react";
import "./UpdateProfile.scss";
import { useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { ReactComponent as UpdateIcon } from "../../assets/icons/edit.svg";
import InputText from "../../components/InputText/InputText";
import Button from "../../components/Button/Button";
import Loader from "../../components/Loader/Loader";
import Textarea from "../../components/Textarea/Textarea";
import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";
import { updateUser } from "../../redux/actions/auth";

const UpdateProfile = () => {
  const navigate = useNavigate();
  const { user } = useSelector((state: any) => state.auth);

  const [userName, setUserName] = useState<string>(user.userName);
  const [bio, setBio] = useState<string>(user.bio);
  const [file, setFile] = useState<any>(null);
  const [fileURL, setFileURL] = useState<string | null>(user.imageUrl);
  const [loading, setLoading] = useState(false);
  const fileInputRef: any = useRef(null);
  const dispatch: any = useDispatch();

  const handleUsernameChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUserName(e.target.value);
  };

  const handleBioChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setBio(e.target.value);
  };

  const handleUpdateUser = () => {
    const userData = {
      userName,
      bio,
      file,
    };

    dispatch(updateUser(user.userId, userData))
      .then(() => {
        setLoading(false);
        navigate(`/profile/${user.userId}`);
      })
      .catch(() => {
        setLoading(false);
      });
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setFileURL(URL.createObjectURL(selectedFile));
    }
  };

  const handleCancel = () => {
    navigate(-1);
  };

  const handleButtonClick = () => {
    if (fileInputRef.current) {
      fileInputRef.current.click();
    }
  };

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <UpdateIcon />
        <h4>Edit Profile</h4>
      </div>
      <div className="update-profile-container">
        <div className="profile-photo">
          {fileURL ? (
            <img src={fileURL} alt="profile" className="profile-img" />
          ) : user.imageUrl ? (
            <img src={user.imageUrl} alt="profile" className="profile-img" />
          ) : (
            <img src={ProfilePlaceholder} alt="profile" className="profile-img" />
          )}

          <div className="profile-input-file">
            <input type="file" name="file" ref={fileInputRef} onChange={handleFileChange} style={{ display: "none" }} />
            <p className="custom-file-button" onClick={handleButtonClick}>
              Change profile photo
            </p>
          </div>
        </div>

        <InputText label="Username" placeholder="Username" onChange={handleUsernameChange} value={userName} />
        <Textarea label="Bio" onChange={handleBioChange} value={bio} />
        <div className="buttons-section">
          <Button variant="outlined" text="Cancel" onClick={handleCancel} />
          <Button onClick={handleUpdateUser} type="submit">
            {loading ? (
              <div className="loader-wrapper">
                <Loader />
                Loading...
              </div>
            ) : (
              "Update Profile"
            )}
          </Button>
        </div>
      </div>
    </div>
  );
};

export default UpdateProfile;

// frameworks-comparison-vue/src/pages/UpdateProfile.vue
<script>
import UpdateIcon from "../assets/icons/edit.svg";
import InputText from "../components/InputText.vue";
import Textarea from "../components/Textarea.vue";
import Button from "../components/Button.vue";
import Loader from "../components/Loader.vue";
import ProfilePlaceholder from "../assets/icons/profile-placeholder.svg";
import { useAuthStore } from "@/stores/useAuthStore";

export default {
  components: {
    InputText,
    Textarea,
    Button,
    Loader,
  },
  data() {
    return {
      userName: "",
      bio: "",
      file: null,
      fileURL: null,
      loading: false,
      authStore: useAuthStore(),
    };
  },
  computed: {
    user() {
      return this.authStore.user;
    },
    ProfilePlaceholder() {
      return ProfilePlaceholder;
    },
    UpdateIcon() {
      return UpdateIcon;
    },
  },
  mounted() {
    this.userName = this.user.userName;
    this.bio = this.user.bio;
  },
  methods: {
    handleUsernameChange(e) {
      this.userName = e.target.value;
    },
    handleBioChange(e) {
      this.bio = e.target.value;
    },
    handleUpdateUser() {
      const userData = {
        userName: this.userName,
        bio: this.bio,
        file: this.file,
      };

      this.loading = true;
      this.authStore
        .updateUser(this.user.userId, userData)
        .then(() => {
          this.loading = false;
          this.$router.push(`/profile/${this.user.userId}`);
        })
        .catch(() => {
          this.loading = false;
        });
    },
    handleFileChange(event) {
      const selectedFile = event.target.files?.[0];
      if (selectedFile) {
        this.file = selectedFile;
        this.fileURL = URL.createObjectURL(selectedFile);
      }
    },
    handleCancel() {
      this.$router.go(-1);
    },
    handleButtonClick() {
      this.$refs.fileInputRef.click();
    },
  },
};
</script>

<template>
  <div class="right-container">
    <div class="title-wrapper">
      <img :src="UpdateIcon" alt="edit" />
      <h4>Edit Profile</h4>
    </div>
    <div class="update-profile-container">
      <div class="profile-photo">
        <img :src="fileURL || user.imageUrl || ProfilePlaceholder" alt="profile" class="profile-img" />
        <div class="profile-input-file">
          <input type="file" name="file" @change="handleFileChange" style="display: none" ref="fileInputRef" />
          <p class="custom-file-button" @click="handleButtonClick">Change profile photo</p>
        </div>
      </div>

      <InputText label="Username" placeholder="Username" :onChange="handleUsernameChange" :value="userName" />
      <Textarea label="Bio" :onChange="handleBioChange" :value="bio" />
      <div class="buttons-section">
        <Button variant="outlined" text="Cancel" @click="handleCancel" />
        <Button @click="handleUpdateUser" type="submit">
          <template v-if="loading">
            <div class="loader-wrapper">
              <Loader />
              Loading...
            </div>
          </template>
          <template v-else> Update Profile </template>
        </Button>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import "src/assets/scss/variables.scss";

.update-profile-container {
  display: flex;
  flex-direction: column;
  gap: 1.75rem;
  margin-top: 1rem;
  .profile-photo {
    display: flex;
    gap: 1rem;
    align-items: center;
    .profile-input-file {
      background: transparent;
      color: $primary-500;
    }
    p {
      color: $primary-500;
      cursor: pointer;
    }
    img {
      width: 6rem;
      height: 6rem;
      border-radius: 100%;
    }
  }
  .buttons-section {
    display: flex;
    gap: 1rem;
    justify-content: flex-end;
    align-items: center;
  }

  .profile-input-file .custom-file-button {
    cursor: pointer;
    color: $primary-500;
  }

  .profile-input-file .custom-file-button:hover {
    color: $primary-700;
  }
}
</style>
