// frameworks-comparison-angular/src/app/pages/post-details/post-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { PostService } from '../../../services/postService';
import { IPost } from '../../../types/index';

@Component({
  selector: 'app-post-details',
  templateUrl: './post-details.component.html',
  styleUrls: ['./post-details.component.scss'],
})
export class PostDetailsComponent implements OnInit {
  post: IPost | null = null;
  isPostLoading: boolean = true;

  constructor(
    private route: ActivatedRoute,
    private location: Location,
    private postService: PostService
  ) {}

  ngOnInit(): void {
    this.getPost();
  }

  getPost(): void {
    const postId = this.route.snapshot.paramMap.get('id');
    if (postId) {
      this.postService.getPostById(postId).subscribe(
        (response: any) => {
          this.post = response.post;
          this.isPostLoading = false;
        },
        (error: any) => {
          console.error('Error fetching post:', error);
        }
      );
    }
  }

  goBack(): void {
    this.location.back();
  }
}

<div class="right-container">
    <div class="title-wrapper">
      <img src="../../../assets/icons/back.svg" alt="back">
      <h4>Back</h4>
    </div>
    <ng-container *ngIf="isPostLoading && !post; else postDetails">
      <app-loader></app-loader>
    </ng-container>
    <ng-template #postDetails>
      <app-post-card [post]="post" (getPosts)="getPost()"></app-post-card>
    </ng-template>
  </div>

// frameworks-comparison-react/src/pages/post-details/PostDetails.tsx
import React, { useEffect, useState } from "react";
import "./PostDetails.scss";
import PostCard from "../../components/post-card/PostCard";
import PostService from "../../services/postService";
import { IPost } from "../../types";
import { ReactComponent as BackIcon } from "../../assets/icons/back.svg";
import { useParams } from "react-router-dom";
import Loader from "../../components/loader/Loader";
import { useNavigate } from "react-router-dom";

const PostDetails = () => {
  const navigate = useNavigate();
  const [post, setPost] = useState<IPost[]>();
  const [isPostLoading, setIsPostLoading] = useState<boolean>(true);
  const { id: postId } = useParams();

  const handleGetPost = () => {
    if (postId) {
      PostService.getPostById(postId)
        .then((response: any) => {
          setPost(response.post);
          setIsPostLoading(false);
        })
        .catch((error: any) => {
          console.error("Error fetching posts:", error);
        });
    }
  };

  useEffect(() => {
    handleGetPost();
  }, []);

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <BackIcon onClick={() => navigate(-1)} style={{ cursor: "pointer" }} />
        <h4>Back</h4>
      </div>
      {isPostLoading && !post ? <Loader /> : <PostCard post={post} getPosts={handleGetPost} />}
    </div>
  );
};

export default PostDetails;
