// frameworks-comparison-angular/src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { Store } from '@ngrx/store';
import * as AuthActions from '../../store/auth.actions';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['../login/login.component.scss'],
})
export class RegisterComponent {
  registerForm: FormGroup = new FormGroup({
    userName: new FormControl(''),
    email: new FormControl(''),
    password: new FormControl(''),
  });
  loading: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);

  constructor(private store: Store) {}

  handleSignUp(): void {
    if (this.registerForm.valid) {
      this.loading.next(true);

      const { userName, email, password } = this.registerForm.value;
      try {
        this.store.dispatch(
          new AuthActions.Register({ userName, email, password })
        );
      } catch (error) {
        console.error('Registration failed:', error);
      } finally {
        this.loading.next(false);
      }
    }
  }
}

<div class="auth-page">
    <div class="left-side">
      <h2 class="logo">PostShare</h2>
      <div class="auth-header">
        <h4>Create a new account</h4>
        <p class="normal-md gray-500">Please enter your details</p>
      </div>
      <form [formGroup]="registerForm" (ngSubmit)="handleSignUp()" class="auth-form">
        <div class="form-group">
          <app-input-text label="Username" placeholder="Username" formControlName="userName"></app-input-text>
        </div>
        <div class="form-group">
          <app-input-text label="Email" placeholder="Email" formControlName="email"></app-input-text>
        </div>
        <div class="form-group">
          <app-input-text type="password" label="Password" placeholder="Password" formControlName="password"></app-input-text>
        </div>
        <app-button type="submit">
          <ng-container *ngIf="loading; else signupText">
            <div class="loader-wrapper">
              <app-loader></app-loader>
              Loading...
            </div>
          </ng-container>
          <ng-template #signupText>Sign Up</ng-template>
        </app-button>
      </form>
      <div class="login-link">
        <span>Already have an account? </span>
        <a routerLink="/sign-in" class="btn btn-link"><app-text-button>Log in</app-text-button></a>
      </div>
    </div>
  </div>

// frameworks-comparison-react/src/pages/Register/Register.tsx
import { useState, ChangeEvent } from "react";
import "../login/Login.scss";
import Button from "../../components/button/Button";
import TextButton from "../../components/text-button/TextButton";
import InputText from "../../components/input-text/InputText";
import { useDispatch } from "react-redux";
import { register } from "../../redux/actions/auth";
import { Link, useNavigate } from "react-router-dom";
import Loader from "../../components/loader/Loader";

const Register = () => {
  let navigate = useNavigate();

  const [userName, setUserName] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [loading, setLoading] = useState(false);

  const dispatch: any = useDispatch();

  const handleUsernameChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUserName(e.target.value);
  };

  const handleEmailChange = (e: ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>) => {
    setPassword(e.target.value);
  };

  const handleSignUp = (e: any) => {
    e.preventDefault();
    setLoading(true);

    dispatch(register(userName, email, password))
      .then(() => {
        setLoading(true);

        setTimeout(() => navigate("/"), 3000);
      })
      .catch(() => {
        setLoading(false);
      });
  };

  return (
    <div className="auth-page">
      <div className="left-side">
        <h2 className="logo">PostShare</h2>
        <div className="auth-header">
          <h4>Create a new account</h4>
          <p className="normal-md gray-500">Please enter your details</p>
        </div>
        <form onSubmit={handleSignUp} className="auth-form">
          <div className="form-group">
            <InputText label="Username" placeholder="Username" onChange={handleUsernameChange} value={userName} />
          </div>
          <div className="form-group">
            <InputText label="Email" placeholder="Email" onChange={handleEmailChange} value={email} />
          </div>
          <div className="form-group">
            <InputText type="password" label="Password" placeholder="Password" onChange={handlePasswordChange} value={password} />
          </div>

          <Button onClick={handleSignUp} type="submit">
            {loading ? (
              <div className="loader-wrapper">
                <Loader />
                Loading...
              </div>
            ) : (
              "Sign Up"
            )}
          </Button>
        </form>
        <div className="login-link">
          <span>Already have an account? </span>
          <Link to="/sign-in">
            <TextButton text="Log in" />
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Register;
