// frameworks-comparison-react/src/pages/all-users/AllUsers.tsx
import React, { useState, useEffect } from "react";
import "./AllUsers.scss";
import { ReactComponent as AllUsersIcon } from "../../assets/icons/people-black.svg";
import UserService from "../../services/userService";
import { IUser } from "../../types";
import UserCard from "../../components/user-card/UserCard";
import Loader from "../../components/loader/Loader";

const AllUsers = () => {
  const [users, setUsers] = useState<IUser[]>([]);
  const [isUsersLoading, setIsUsersLoading] = useState<boolean>(false);

  useEffect(() => {
    setIsUsersLoading(true);
    UserService.getUsers()
      .then((response) => {
        setUsers(response.users);
        setIsUsersLoading(false);
      })
      .catch((error: any) => {
        console.error("Error fetching users:", error);
      });
  }, []);

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <AllUsersIcon />
        <h4>Users</h4>
      </div>
      {isUsersLoading && !users ? (
        <Loader />
      ) : (
        <div className="users-list">
          {users.map((user, userId) => (
            <React.Fragment key={userId}>
              <UserCard user={user} />
            </React.Fragment>
          ))}
        </div>
      )}
    </div>
  );
};

export default AllUsers;

// frameworks-comparison-angular/src/app/pages/all-users/all-users.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from '../../../services/userService';
import { IUser } from '../../../types/index';

@Component({
  selector: 'app-all-users',
  templateUrl: './all-users.component.html',
  styleUrls: ['./all-users.component.scss'],
})
export class AllUsersComponent implements OnInit {
  users: IUser[] = [];
  isUsersLoading: boolean = false;

  constructor(private userService: UserService) {}

  ngOnInit(): void {
    this.isUsersLoading = true;
    this.userService.getUsers().subscribe(
      (response) => {
        this.users = response.users;

        this.isUsersLoading = false;
      },
      (error) => {
        console.error('Error fetching users:', error);
        this.isUsersLoading = false;
      }
    );
  }
}

<div class="right-container">
    <div class="title-wrapper">
      <img src="../../assets/icons/people-black.svg" alt="people">
      <h4>Users</h4>
    </div>
    <div *ngIf="isUsersLoading && !users; else usersList" class="loader-container">
      <app-loader></app-loader>
    </div>
    <ng-template #usersList>
      <div class="users-list">
        <app-user-card *ngFor="let user of users; let userId = index" [user]="user"></app-user-card>
      </div>
    </ng-template>
  </div>
