// frameworks-comparison-react/src/components/Search/Search.tsx
import React from "react";
import "./Search.scss";
import { ReactComponent as SearchIcon } from "../../assets/icons/search.svg";

interface SearchProps {
  placeholder?: string;
  onSearch: (query: string) => void;
  value: string;
  onChange: any;
}

const Search = ({ placeholder, onSearch, value, onChange }: SearchProps) => {
  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    onChange(event.target.value);
  };

  const handleKeyPress = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter") {
      onSearch(value);
    }
  };
  return (
    <div className="search-container">
      <input
        type="search"
        className="input-search"
        placeholder={placeholder}
        value={value}
        onChange={handleInputChange}
        onKeyPress={handleKeyPress}
      />
      <SearchIcon className="search-icon" />
    </div>
  );
};

export default Search;

// frameworks-comparison-angular/src/app/components/search/search.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss'],
})
export class SearchComponent {
  @Input() placeholder: string | undefined;
  @Input() value: string | undefined;
  @Input() onChange: ((query: string) => void) | undefined;
  inputValue: string = '';

  constructor() {}

  handleInputChange(event: any) {
    if (this.onChange) {
      this.onChange(event.target.value);
    }
  }

  handleKeyPress(event: any) {
    if (event.key === 'Enter' && this.onChange) {
      this.onChange(this.inputValue);
    }
  }
}

  <div class="search-container">
    <input
      type="search"
      class="input-search"
      [placeholder]="placeholder"
      [(ngModel)]="searchQuery"
      (input)="updateSearchQuery()"
      (keypress)="handleKeyPress($event)"
    />
    <img src="assets/icons/search.svg" alt="search" class="search-icon" />
  </div>
