// frameworks-comparison-react/src/components/Textarea/Textarea.tsx
import { ChangeEvent } from "react";
import "./Textarea.scss";

type TextareaProps = {
  label?: string;
  value: string;
  placeholder?: string;
  onChange: (event: ChangeEvent<HTMLTextAreaElement>) => void;
  size?: "small" | "medium" | "large";
};

const Textarea = ({ label, value, placeholder, onChange, size = "medium" }: TextareaProps) => {
  return (
    <div className="textarea-container">
      {label && <label className={["textarea-label", `textarea-label--${size}`].join(" ")}>{label}</label>}
      <textarea className={["textarea-text", `textarea-text--${size}`].join(" ")} value={value} placeholder={placeholder} onChange={onChange} />
    </div>
  );
};

export default Textarea;

// frameworks-comparison-angular/src/app/components/textarea/textarea.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-textarea',
  templateUrl: './textarea.component.html',
  styleUrls: ['./textarea.component.scss'],
})
export class TextareaComponent {}

<div class="textarea-container">
  <label *ngIf="label" [class]="'textarea-label textarea-label--' + size">{{
    label
  }}</label>
  <textarea
    [class]="'textarea-text textarea-text--' + size"
    [(ngModel)]="value"
    (input)="onChange(value)"
    [placeholder]="placeholder"
  ></textarea>
</div>
