// frameworks-comparison-angular/src/app/components/user-card/user-card.component.ts
import { Component, Input } from '@angular/core';
import { IUser } from 'src/types';

@Component({
  selector: 'app-user-card',
  templateUrl: './user-card.component.html',
  styleUrls: ['./user-card.component.scss'],
})
export class UserCardComponent {
  @Input() user: IUser | undefined;
  ProfilePlaceholder: string = '../../../assets/icons/profile-placeholder.svg';
}

<div class="user-item">
    <a [routerLink]="['/profile', user?._id]" class="user-card">
      <img [src]='user?.imageUrl ? user?.imageUrl : "../../../assets/icons/profile-placeholder.svg"' alt="profile" class="user-card-img" />
      <div class="user-info">
        <p class="user-username">{{ user?.userName }}</p>
      </div>
      <app-button text="See profile"></app-button>
    </a>
  </div>

// frameworks-comparison-react/src/components/UserCard/UserCard.tsx
import React from "react";
import "./UserCard.scss";
import { IUser } from "../../types";
import { Link } from "react-router-dom";
import Button from "../Button/Button";

import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";

type UserCardProps = {
  user: IUser;
};

const UserCard = ({ user }: UserCardProps) => {
  return (
    <>
      <div className="user-item" key={user._id}>
        <Link to={`/profile/${user._id}`} className="user-card">
          <img src={ProfilePlaceholder} alt="profile" />
          <div className="user-info">
            <p className="user-username">{user.userName}</p>
          </div>
          <Button text="See profile" />
        </Link>
      </div>
    </>
  );
};

export default UserCard;
