// frameworks-comparison-angular/src/app/components/left-sidebar/left-sidebar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { sidebarLinks } from '../../../constants/index';
import { INavLink } from '../../../types';
// import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-left-sidebar',
  templateUrl: './left-sidebar.component.html',
  styleUrls: ['./left-sidebar.component.scss'],
})
export class LeftSidebarComponent {
  sidebarLinks: INavLink[] = sidebarLinks;
  user: any;

  constructor(
    // private authService: AuthService,
    public router: Router
  ) {
    // this.user = this.authService.getCurrentUser(); // Implementacja tej metody zależy od logiki w AuthService
  }

  handleLogout() {
    // this.authService.logout(); // Implementacja metody logout w AuthService
    this.router.navigate(['/sign-in']);
  }
}

<nav class="left-sidebar">
    <div class="sidebar-wrapper">
      <a routerLink="/">
        <h4>PostShare</h4>
      </a>

      <a [routerLink]="['/profile', user?.userId]">
        <div class="sidebar-profile">
          <img [src]="user?.imageUrl ? user?.imageUrl : 'assets/icons/profile-placeholder.svg'" alt="profile" />
          <div class="user-info">
            <p class="username">{{ user?.userName }}</p>
          </div>
        </div>
      </a>

      <ul>
        <li *ngFor="let link of sidebarLinks" [class.left-sidebar-link]="true"
        [class.left-sidebar-link--active]="router.url === link.route"
        >
          <a [routerLink]="link.route">
            <img [src]="link.imgURL" alt="{{ link.label }}" />
            {{ link.label }}
          </a>
        </li>
      </ul>
    </div>

    <ul>
      <li class="left-sidebar-link" (click)="handleLogout()">
        <div class="logout-button">
          <img src="assets/icons/logout.svg" alt="logout" />
          Logout
        </div>
      </li>
    </ul>
  </nav>

// frameworks-comparison-react/src/components/left-sidebar/LeftSidebar.tsx
import React from "react";
import "./LeftSidebar.scss";
import { Link, NavLink, useLocation, useNavigate } from "react-router-dom";
import { sidebarLinks } from "../../constants/index";
import { INavLink } from "../../types";
import Logout from "../../assets/icons/logout.svg";
import { useDispatch, useSelector } from "react-redux";
import { logout } from "../../redux/actions/auth";

import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";

const LeftSidebar = () => {
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const { user } = useSelector((state: any) => {
    return state.auth;
  });

  const dispatch: any = useDispatch();

  const handleLogout = () => {
    dispatch(logout());
    navigate("/sign-in");
  };

  return (
    <nav className="left-sidebar">
      <div className="sidebar-wrapper">
        <Link to="/">
          <h4>PostShare</h4>
        </Link>

        <Link to={`/profile/${user?.userId}`}>
          <div className="sidebar-profile">
            <img src={user?.imageUrl ? user?.imageUrl : ProfilePlaceholder} alt="profile" />
            <div className="user-info">
              <p className="username">{user?.userName}</p>
            </div>
          </div>
        </Link>

        <ul>
          {sidebarLinks.map((link: INavLink) => {
            const isActive = pathname === link.route;

            return (
              <li
                key={link.label}
                className={["left-sidebar-link", `${isActive ? "left-sidebar-link--active" : "left-sidebar-link--inactive"}`].join(" ")}
              >
                <NavLink to={link.route}>
                  <img src={link.imgURL} alt={link.label} />
                  {link.label}
                </NavLink>
              </li>
            );
          })}
        </ul>
      </div>

      <ul>
        <li className="left-sidebar-link" onClick={handleLogout}>
          <div className="logout-button">
            <img src={Logout} alt="logout" />
            Logout
          </div>
        </li>
      </ul>
    </nav>
  );
};

export default LeftSidebar;
