// frameworks-comparison-react/src/layouts/root-layout/RootLayout.tsx
import { Outlet } from "react-router-dom";
import LeftSidebar from "../../components/left-sidebar/LeftSidebar";
import "./RootLayout.scss";

const RootLayout = () => {
  return (
    <div className="root-layout">
      <LeftSidebar />

      <Outlet />
    </div>
  );
};

export default RootLayout;

// frameworks-comparison-angular/src/app/layouts/root-layout/root-layout.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root-layout',
  templateUrl: './root-layout.component.html',
  styleUrls: ['./root-layout.component.scss'],
})
export class RootLayoutComponent {}

<div class="root-layout">
    <app-left-sidebar></app-left-sidebar>

    <router-outlet></router-outlet>
  </div>
