// frameworks-comparison-react/src/layouts/root-layout/RootLayout.tsx
import { Outlet } from "react-router-dom";
import LeftSidebar from "../../components/left-sidebar/LeftSidebar";
import "./RootLayout.scss";

const RootLayout = () => {
  return (
    <div className="root-layout">
      <LeftSidebar />

      <Outlet />
    </div>
  );
};

export default RootLayout;

// frameworks-comparison-vue/src/layouts/RootLayout.vue
<script setup lang="ts">
import LeftSidebar from "@/components/LeftSidebar.vue";
</script>

<template>
  <div className="root-layout">
    <LeftSidebar />
    <RouterView />
  </div>
</template>

<style scoped lang="scss">
@import "@/assets/scss/variables.scss";

.root-layout {
  display: flex;
  width: -webkit-fill-available;
}
</style>
