// frameworks-comparison-react/src/pages/CreatePost/CreatePost.tsx
import React, { useState } from "react";
import "./CreatePost.scss";
import Textarea from "../../components/Textarea/Textarea";
import InputText from "../../components/InputText/InputText";
import Button from "../../components/Button/Button";
import { ReactComponent as CreatePostIcon } from "../../assets/icons/gallery-add-black.svg";
import { useNavigate } from "react-router-dom";
import PostService from "../../services/postService";
import { useSelector } from "react-redux";
import Loader from "../../components/Loader/Loader";

const CreatePost = () => {
  const navigate = useNavigate();
  const [caption, setCaption] = useState("");
  const [location, setLocation] = useState("");
  const [file, setFile] = useState<any>(null);
  const [fileURL, setFileURL] = useState<string | null>(null);
  const [tags, setTags] = useState("");
  const [loading, setLoading] = useState(false);
  const { userId, imageUrl, userName } = useSelector((state: any) => {
    return state.auth.user;
  });

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setFileURL(URL.createObjectURL(selectedFile));
    }
  };

  const handleCreatePost = (e: any) => {
    e.preventDefault();

    setLoading(true);

    PostService.createPost({ creator: { userId, imageUrl, userName }, caption, file, location, tags })
      .then(() => {
        navigate("/");
        setLoading(false);
      })
      .catch(() => {
        setLoading(false);
      });
  };

  const handleCancel = () => {
    navigate(-1);
  };

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <CreatePostIcon />
        <h4>Create Post</h4>
      </div>

      <form onSubmit={handleCreatePost} className="create-post-form">
        <div className="caption-section">
          <Textarea label="Caption" value={caption} onChange={(e) => setCaption(e.target.value)} />
        </div>

        <div className="image-upload-section">
          <label htmlFor="image-upload">Add Photos</label>

          <input type="file" name="file" onChange={handleFileChange} />
          <button type="submit">Upload</button>

          {fileURL && <img src={fileURL} alt="Selected File" />}
        </div>

        <div className="location-section">
          <InputText label="Add Location" value={location} onChange={(e) => setLocation(e.target.value)} />
        </div>

        <div className="tags-section">
          <InputText
            label="Add Tags (separate by comma “,”)"
            placeholder="Travel, Art, Sport"
            value={tags}
            onChange={(e) => setTags(e.target.value)}
          />
        </div>

        <div className="buttons-section">
          <Button variant="outlined" text="Cancel" onClick={handleCancel} />
          <Button onClick={handleCreatePost} type="submit">
            {loading ? (
              <div className="loader-wrapper">
                <Loader />
                Loading...
              </div>
            ) : (
              "Create Post"
            )}
          </Button>
        </div>
      </form>
    </div>
  );
};

export default CreatePost;

// frameworks-comparison-angular/src/app/pages/create-post/create-post.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../services/authService';
import { PostService } from '../../../services/postService';

@Component({
  selector: 'app-create-post',
  templateUrl: './create-post.component.html',
  styleUrls: ['./create-post.component.scss'],
})
export class CreatePostComponent {
  caption: string = '';
  location: string = '';
  tags: string = '';
  file: File | null = null;
  fileURL: string | null = null;
  loading: boolean = false;

  constructor(
    private authService: AuthService,
    private postService: PostService,
    private router: Router
  ) {}

  handleFileChange(event: any): void {
    const selectedFile = event.target.files?.[0];
    if (selectedFile) {
      this.file = selectedFile;
      this.fileURL = URL.createObjectURL(selectedFile);
    }
  }

  handleCreatePost(event: any): void {
    event.preventDefault();

    // const { userId, imageUrl, userName } = this.authService.getCurrentUser();

    // this.loading = true;

    // this.postService
    //   .createPost({
    //     creator: { userId, imageUrl, userName },
    //     caption: this.caption,
    //     file: this.file,
    //     location: this.location,
    //     tags: this.tags,
    //   })
    //   .subscribe(
    //     () => {
    //       this.router.navigate(['/']);
    //       this.loading = false;
    //     },
    //     () => {
    //       this.loading = false;
    //     }
    //   );
  }

  handleCancel(): void {
    this.router.navigate(['/']);
  }
}

<div class="right-container">
    <div class="title-wrapper">
      <img src="../../../assets/icons/gallery-add-black.svg" alt="gallery-add-black">
      <h4>Create Post</h4>
    </div>

    <form (submit)="handleCreatePost($event)" class="create-post-form">
      <div class="caption-section">
        <app-textarea label="Caption" [(ngModel)]="caption"></app-textarea>
      </div>

      <div class="image-upload-section">
        <label for="image-upload">Add Photos</label>

        <div class="add-photo-wrapper" style="margin-top: 8px;">
          <img src="../../../assets/icons/file-upload.svg" alt="">
          <span>Upload a photo in PNG, JPG or SVG format</span>
          <input type="file" id="upload" (change)="handleFileChange($event)" hidden />
          <label for="upload" class="custom-file-button">Select from computer</label>

          <img *ngIf="fileURL" [src]="fileURL" alt="Selected File" />
        </div>
      </div>

      <div class="location-section">
        <app-input-text label="Add Location" [(ngModel)]="location"></app-input-text>
      </div>

      <div class="tags-section">
        <app-input-text label="Add Tags (separate by comma “,”)" placeholder="Travel, Art, Sport" [(ngModel)]="tags"></app-input-text>
      </div>

      <div class="buttons-section">
        <button class="btn btn-outlined" type="button" (click)="handleCancel()">Cancel</button>
        <button class="btn" type="submit">
          <ng-container *ngIf="loading; else createPostText">
            <div class="loader-wrapper">
              <app-loader></app-loader>
              Loading...
            </div>
          </ng-container>
          <ng-template #createPostText>Create Post</ng-template>
        </button>
      </div>
    </form>
  </div>
