// frameworks-comparison-react/src/pages/Saved/Saved.tsx
import React, { useEffect, useState } from "react";
import "./Saved.scss";
import { ReactComponent as SavedIcon } from "../../assets/icons/bookmark-black.svg";
import Loader from "../../components/loader/Loader";
import { IPost } from "../../types";
import PostService from "../../services/postService";
import { useSelector } from "react-redux";
import GridPostList from "../../components/grid-post-list/GridPostList";

const Saved = () => {
  const [isPostsLoading, setIsPostsLoading] = useState<boolean>(false);
  const [savedPosts, setSavedPosts] = useState<IPost[]>([]);

  const { user } = useSelector((state: any) => {
    return state.auth;
  });

  useEffect(() => {
    setIsPostsLoading(true);
    PostService.getLikedPosts(user.userId)
      .then((response) => {
        setSavedPosts(response.likedPosts);
        setIsPostsLoading(false);
      })
      .catch((error: any) => {
        console.error("Error fetching posts:", error);
      });
  }, []);

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <SavedIcon />
        <h4>Saved</h4>
      </div>
      {isPostsLoading && !savedPosts ? <Loader /> : <GridPostList posts={savedPosts} />}
    </div>
  );
};

export default Saved;

// frameworks-comparison-angular/src/app/pages/saved/saved.component.ts
import { Component, OnInit } from '@angular/core';
import { IPost, IUser } from '../../../types/index';
import { PostService } from '../../../services/postService';
import { AuthService } from '../../../services/authService';
import * as AuthActions from '../../store/auth.actions';
import { BehaviorSubject, Observable, first } from 'rxjs';
import { Store, select } from '@ngrx/store';

@Component({
  selector: 'app-saved',
  templateUrl: './saved.component.html',
  styleUrls: ['./saved.component.scss'],
})
export class SavedComponent implements OnInit {
  isPostsLoading: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(
    false
  );
  savedPosts: IPost[] = [];
  auth$: Observable<any>;
  user: any = null;

  constructor(
    private postService: PostService,
    private authService: AuthService,
    private store: Store<{ auth: any }>
  ) {
    this.auth$ = this.store.pipe(select('auth'));
    this.auth$.subscribe((auth) => {
      this.user = auth.user;
    });
  }

  ngOnInit(): void {
    this.isPostsLoading.next(true);

    if (this?.user?.userId) {
      this.postService.getLikedPosts(this.user?.userId).subscribe(
        (response) => {
          this.savedPosts = response.likedPosts;

          this.isPostsLoading.next(false);
          console.log(this.savedPosts);
          console.log(this.isPostsLoading.value);
        },
        (error) => {
          console.error('Error fetching posts:', error);
          this.isPostsLoading.next(false);
        }
      );
    }
  }
}

<div class="right-container">
    <div class="title-wrapper">
      <img src="../../../assets/icons/bookmark-black.svg" alt="bookmark">
      <h4>Saved</h4>
    </div>
    <div *ngIf="isPostsLoading.value && !savedPosts" class="loader-wrapper">
      <app-loader></app-loader>
      Loading...
    </div>

    <app-grid-post-list *ngIf="!isPostsLoading.value && savedPosts" [posts]="savedPosts"></app-grid-post-list>
  </div>
