// frameworks-comparison-react/src/layouts/root-layout/RootLayout.tsx
import { Outlet } from "react-router-dom";
import LeftSidebar from "../../components/left-sidebar/LeftSidebar";
import "./RootLayout.scss";

const RootLayout = () => {
  return (
    <div className="root-layout">
      <LeftSidebar />

      <Outlet />
    </div>
  );
};

export default RootLayout;

// frameworks-comparison-vue/src/layouts/RootLayout/RootLayout.vue
<template>
  <div class="root-layout">
    <left-sidebar />
    <router-view />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import LeftSidebar from '../../components/LeftSidebar.vue';

export default defineComponent({
  name: 'RootLayout',
  components: {
    LeftSidebar
  }
});
</script>

<style scoped lang="scss">
.root-layout {
  display: flex;
   width: -webkit-fill-available;
}
</style>
