// frameworks-comparison-angular/src/app/components/grid-post-list/grid-post-list.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-grid-post-list',
  templateUrl: './grid-post-list.component.html',
  styleUrls: ['./grid-post-list.component.scss'],
})
export class GridPostListComponent {
  @Input() posts: any[] = [];
  @Input() showUser: boolean = true;
  ProfilePlaceholder: string = '../../../assets/icons/profile-placeholder.svg';
}

<ul class="grid-container">
  <li *ngFor="let post of posts" class="relative min-w-80 h-80">
    <a [routerLink]="'/posts/' + post._id" class="grid-post_link">
      <img [src]='post.imageUrl ? post.imageUrl : "../../../assets/icons/profile-placeholder.svg"' alt="post" class="h-full w-full object-cover" />
    </a>

    <div class="grid-post_user" *ngIf="showUser">
      <div class="grid-post_user-wrapper">
        <img [src]="post.creator?.imageUrl || 'path/to/default/image'" alt="creator" class="w-8 h-8 rounded-full" />
        <p class="line-clamp-1">{{ post.creator?.userName }}</p>
      </div>
    </div>
  </li>
</ul>

// frameworks-comparison-react/src/components/grid-post-list/GridPostList.tsx
import "./GridPostList.scss";
import { IPost } from "../../types";
import { Link } from "react-router-dom";
import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";

type GridPostListProps = {
  posts: IPost[];
  showUser?: boolean;
};

const GridPostList = ({ posts, showUser = true }: GridPostListProps) => {
  return (
    <ul className="grid-container">
      {posts.map((post: IPost) => (
        <li key={post._id} className="relative min-w-80 h-80">
          <Link to={`/posts/${post._id}`} className="grid-post_link">
            <img src={post.imageUrl} alt="post" className="h-full w-full object-cover" />
          </Link>

          <div className="grid-post_user">
            {showUser && (
              <div className="grid-post_user-wrapper">
                <img src={post.creator.imageUrl || ProfilePlaceholder} alt="creator" className="w-8 h-8 rounded-full" />
                <p className="line-clamp-1">{post.creator.userName}</p>
              </div>
            )}
          </div>
        </li>
      ))}
    </ul>
  );
};

export default GridPostList;
