// frameworks-comparison-react/src/components/Button/Button.tsx
import React from "react";
import "./Button.scss";

type ButtonProps = {
  variant?: "primary" | "outlined";
  text?: string;
  onClick?: any;
  size?: "small" | "medium" | "large";
  iconLeft?: JSX.Element;
  iconRight?: JSX.Element;
  children?: any;
  type?: "submit" | "reset" | "button";
};

const Button = ({ text, variant = "primary", onClick, size = "medium", iconLeft, iconRight, children, type = "button" }: ButtonProps) => {
  return (
    <button type={type} className={["custom-button", `custom-button--${variant}`, `custom-button--${size}`].join(" ")} onClick={onClick}>
      {children}
      {iconLeft}
      {text}
      {iconRight}
    </button>
  );
};

export default Button;

// frameworks-comparison-angular/src/app/components/button/button.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss'],
})
export class ButtonComponent {
  @Input() variant: 'primary' | 'outlined' = 'primary';
  @Input() text: string | undefined;
  @Input() onClick: (() => void) | undefined;
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Input() iconLeft: string | undefined;
  @Input() iconRight: string | undefined;
  @Input() type: 'submit' | 'reset' | 'button' = 'button';

  constructor() {}

  handleClick() {
    if (this.onClick) {
      this.onClick();
    }
  }
}

<button [type]="type" (click)="handleClick()" class="custom-button" [ngClass]="['custom-button--' + variant, 'custom-button--' + size]">
    {{ iconLeft }}
    {{ text }}
    {{ iconRight }}
  </button>
