// frameworks-comparison-react/src/components/post-card/PostCard.tsx
import "./PostCard.scss";
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";
import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";
import PostService from "../../services/postService";
import moment from "moment";
import LikeIcon from "../../assets/icons/like.svg";
import LikedIcon from "../../assets/icons/liked.svg";

type PostCardProps = {
  post: any;
  getPosts: any;
};

const PostCard = ({ post, getPosts }: PostCardProps) => {
  const { user } = useSelector((state: any) => {
    return state.auth;
  });

  const handleLikePost = () => {
    PostService.likePostById(post._id)
      .then((response) => {
        getPosts();
      })
      .catch((error: any) => {});
  };

  const handleUnlikePost = () => {
    PostService.unlikePostById(post._id)
      .then((response) => {
        getPosts();
      })
      .catch((error: any) => {});
  };

  return (
    <div className="post-card">
      <div className="post-header">
        <Link to={`/profile/${post.creator.userId}`}>
          <img src={post.creator?.imageUrl || ProfilePlaceholder} className="post-avatar" alt="creator" />
        </Link>

        <div className="post-details">
          <p className="post-creator">{post.creator.userName}</p>
          <div className="post-date-location">
            <p>{moment(post.createdAt, "YYYYMMDD, h:mm:ss a").calendar()}</p>
            <p>{post.location}</p>
          </div>
        </div>
      </div>

      <div className="post-body">
        <Link to={`/posts/${post._id}`}>
          <p className="post-title">{post.caption}</p>
        </Link>
        <div className="post-tags">
          {post.tags.map((tag: string, index: string) => (
            <span>{`#${tag}`}</span>
          ))}
        </div>

        <img src={post.imageUrl} alt="post" className="post-img" />
        <div className="likes-wrapper">
          {post.likes.includes(user.userId) ? (
            <img src={LikedIcon} alt="like" className="like-icon" onClick={handleUnlikePost} />
          ) : (
            <img src={LikeIcon} alt="like" className="like-icon" onClick={handleLikePost} />
          )}

          <span>{post.likes.length}</span>
        </div>
      </div>
    </div>
  );
};

export default PostCard;

// frameworks-comparison-angular/src/app/components/post-card/post-card.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../services/authService';
import { PostService } from '../../../services/postService';
import moment from 'moment';
import { Observable } from 'rxjs';
import { Store, select } from '@ngrx/store';

@Component({
  selector: 'app-post-card',
  templateUrl: './post-card.component.html',
  styleUrls: ['./post-card.component.scss'],
})
export class PostCardComponent {
  @Input() post: any;
  @Output() getPosts: EventEmitter<any> = new EventEmitter();
  auth$: Observable<any>;
  user: any = null;

  constructor(
    private postService: PostService,
    private authService: AuthService,
    private router: Router,
    private store: Store<{ auth: any }>
  ) {
    this.auth$ = this.store.pipe(select('auth'));
    this.auth$.subscribe((auth) => {
      this.user = auth.user;
    });
  }

  handleLikePost(): void {
    this.postService.likePostById(this.post._id).subscribe(
      (response: any) => {
        this.getPosts.emit();
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
  }

  handleUnlikePost(): void {
    this.postService.unlikePostById(this.post._id).subscribe(
      (response: any) => {
        this.getPosts.emit();
      },
      (error: any) => {
        console.error('Error fetching posts:', error);
      }
    );
  }

  formatPostDate(date: string): string {
    return moment(date, 'YYYYMMDD, h:mm:ss a').calendar();
  }
}

<div class="post-card">
  <div class="post-header">
    <a [routerLink]="'/profile/' + post.creator.userId">
      <img [src]="post.creator?.imageUrl || '../../../assets/icons/profile-placeholder.svg'" class="post-avatar" alt="creator" />
    </a>
    <div class="post-details">
      <p class="post-creator">{{ post.creator.userName }}</p>
      <div class="post-date-location">
        <p>{{ formatPostDate(post.createdAt) }}</p>
        <p>{{ post.location }}</p>
      </div>
    </div>
  </div>

  <div class="post-body">
    <a [routerLink]="'/posts/' + post._id">
      <p class="post-title">{{ post.caption }}</p>
    </a>
    <div class="post-tags">
      <span *ngFor="let tag of post.tags">{{ '#' + tag }}</span>
    </div>
    <img [src]="post.imageUrl" alt="post" class="post-img" />
    <div class="likes-wrapper">
      <img [src]="post.likes.includes(user.userId) ? '../../../assets/icons/liked.svg' : '../../../assets/icons/like.svg'" alt="like" class="like-icon" (click)="post.likes.includes(user.userId) ? handleUnlikePost() : handleLikePost()" />
      <span>{{ post.likes.length }}</span>
    </div>
  </div>
</div>
