// frameworks-comparison-react/src/components/InputText/InputText.tsx
import React, { ChangeEvent } from "react";
import "./InputText.scss";

interface InputTextProps {
  label?: string;
  placeholder?: string;
  size?: "small" | "medium" | "large";
  onChange: (event: ChangeEvent<HTMLInputElement>) => void;
  value: string;
  type?: string;
}

const InputText = ({ label, placeholder, size = "medium", onChange, value, type = "text" }: InputTextProps) => {
  return (
    <div className="input-container">
      {label && <label className={["input-label", `input-label--${size}`].join(" ")}>{label}</label>}
      <input type={type} placeholder={placeholder} onChange={onChange} value={value} className={["input-text", `input-text--${size}`].join(" ")} />
    </div>
  );
};

export default InputText;

// frameworks-comparison-angular/src/app/components/input-text/input-text.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-input-text',
  templateUrl: './input-text.component.html',
  styleUrls: ['./input-text.component.scss'],
})
export class InputTextComponent {
  @Input() label: string | undefined;
  @Input() placeholder: string | undefined;
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Input() value: string | undefined;
  @Input() type: string = 'text';
  @Output() valueChange: EventEmitter<string> = new EventEmitter<string>();

  constructor() {}

  onChange(event: any) {
    this.valueChange.emit(event.target.value);
  }
}

<div class="input-container">
    <label *ngIf="label" [class]="'input-label input-label--' + size">{{ label }}</label>
    <input [type]="type" [placeholder]="placeholder" [value]="value" (input)="onChange($event)" class="input-text" [class.input-text--small]="size === 'small'" [class.input-text--medium]="size === 'medium'" [class.input-text--large]="size === 'large'" />
  </div>
