// frameworks-comparison-angular/src/app/pages/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Observable } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
import { IUser } from '../../../types/index';
import { AuthService } from '../../../services/authService';
import { UserService } from '../../../services/userService';
import { Store, select } from '@ngrx/store';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
})
export class ProfileComponent implements OnInit {
  activeUser: IUser | undefined;
  auth$: Observable<any>;
  user: any = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private authService: AuthService,
    private userService: UserService,
    private store: Store<{ auth: any }>
  ) {
    this.auth$ = this.store.pipe(select('auth'));
    this.auth$.subscribe((auth) => {
      this.user = auth.user;
    });
  }

  ngOnInit(): void {
    this.route.params
      .pipe(
        map((params) => params['id']),
        switchMap((userId) => this.userService.getUserById(userId))
      )
      .subscribe(
        (response) => (this.activeUser = response.user),
        (error) => console.error('Error fetching user:', error)
      );
  }

  handleEditProfile(): void {
    if (this.activeUser) {
      this.router.navigate(['/update-profile', this.activeUser._id]);
    }
  }
}

<div class="right-container">
    <div class="user-profile">
      <div class="profile-header">
        <img [src]='activeUser?.imageUrl ? activeUser?.imageUrl : "../../../assets/icons/profile-placeholder.svg"' alt="profile" class="profile-img" />
        <div class="profile-info">
          <p class="profile-username">{{ activeUser?.userName }}</p>
          <p class="profile-bio">{{ activeUser?.bio }}</p>
        </div>

        <app-button *ngIf="activeUser && user?.userId === activeUser?._id" class="btn btn-primary" (click)="handleEditProfile()">Edit Profile</app-button>
      </div>
    </div>
  </div>

// frameworks-comparison-react/src/pages/Profile/Profile.tsx
import { useState, useEffect } from "react";
import "./Profile.scss";
import { useNavigate, useParams } from "react-router-dom";
import Button from "../../components/button/Button";
import { IUser } from "../../types";
import { useSelector } from "react-redux";
import UserService from "../../services/userService";

import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";

const Profile = () => {
  const navigate = useNavigate();

  const { id: userId } = useParams();
  const { user } = useSelector((state: any) => state.auth);

  const [activeUser, setActiveUser] = useState<IUser>();

  useEffect(() => {
    if (userId) {
      UserService.getUserById(userId)
        .then((response) => {
          setActiveUser(response.user);
        })
        .catch((error: any) => {
          console.error("Error fetching users:", error);
        });
    }
  }, []);

  const handleEditProfile = () => {
    if (activeUser) {
      navigate(`/update-profile/${activeUser._id}`);
    }
  };

  return (
    <div className="right-container">
      <div className="user-profile">
        <div className="profile-header">
          <img src={activeUser?.imageUrl ? activeUser?.imageUrl : ProfilePlaceholder} alt="profile" className="profile-img" />
          <div className="profile-info">
            <p className="profile-username">{activeUser?.userName}</p>
            <p className="profile-bio">{activeUser?.bio}</p>
          </div>

          {user.userId === userId ? <Button text="Edit Profile" onClick={handleEditProfile} /> : null}
        </div>
      </div>
    </div>
  );
};

export default Profile;
