// frameworks-comparison-react/src/components/UserCard/UserCard.tsx
import React from "react";
import "./UserCard.scss";
import { IUser } from "../../types";
import { Link } from "react-router-dom";
import Button from "../Button/Button";

import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";

type UserCardProps = {
  user: IUser;
};

const UserCard = ({ user }: UserCardProps) => {
  return (
    <>
      <div className="user-item" key={user._id}>
        <Link to={`/profile/${user._id}`} className="user-card">
          <img src={ProfilePlaceholder} alt="profile" />
          <div className="user-info">
            <p className="user-name">{user.name}</p>
            <p className="user-username">@{user.username}</p>
          </div>
          <Button text="See profile" />
        </Link>
      </div>
    </>
  );
};

export default UserCard;

// frameworks-comparison-vue/src/components/UserCard.vue
<script setup lang="ts">
import { IUser } from "@/types";
import { defineProps } from "vue";
import Button from "@/components/Button.vue";
import ProfilePlaceholderIcon from "../assets/icons/profile-placeholder.svg";

const props = defineProps<{
  user: IUser;
}>();
</script>

<template>
  <div class="user-item">
    <router-link :to="`/profile/${user._id}`" class="user-card">
      <img :src="ProfilePlaceholderIcon" alt="profile" />
      <div class="user-info">
        <p class="user-username">{{ user.userName }}</p>
      </div>
      <Button text="See profile" />
    </router-link>
  </div>
</template>

<style scoped lang="scss">
@import "src/assets/scss/variables.scss";

.user-item {
  width: 100%;
  .user-card {
    display: flex;
    flex-direction: column;
    border-radius: 20px;
    gap: 1rem;
    border: 1px solid $gray-200;
    padding: 2rem 1.25rem;
    align-items: center;
    justify-content: center;
    .user-info {
      display: flex;
      align-items: center;
      flex-direction: column;

      .user-name {
        color: $black;
        font-weight: bold;
        font-size: 18px;
      }
      .user-username {
        color: $gray-500;
        font-size: 12px;
      }
    }
  }
}
</style>
