// frameworks-comparison-react/src/layouts/AuthLayout/AuthLayout.tsx
import React from "react";
import { Outlet, Navigate } from "react-router-dom";
import { useSelector } from "react-redux";
import "./AuthLayout.scss";
import AuthImage from "../../assets/images/auth-image.png";

const AuthLayout = () => {
  const { isLoggedIn } = useSelector((state: any) => {
    return state.auth;
  });

  return (
    <>
      {isLoggedIn ? (
        <Navigate to="/" />
      ) : (
        <>
          <div className="auth-layout">
            <Outlet />
          </div>
          <div className="auth-image">
            <img src={AuthImage} alt="logo" />
          </div>
        </>
      )}
    </>
  );
};

export default AuthLayout;

// frameworks-comparison-vue/src/layouts/AuthLayout/AuthLayout.vue
<template>
  <div v-if="!isLoggedIn" class="auth-layout">
    <router-view/>
    <div class="auth-image">
      <img src="../../assets/images/auth-image.png" alt="logo" />
    </div>
  </div>
  <router-view v-else />
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useStore } from 'vuex';

export default defineComponent({
  name: 'AuthLayout',
  computed: {
    isLoggedIn() {
      return useStore().state.isLoggedIn;
    }
  }
});
</script>

<style scoped lang="scss">
@import "src/assets/scss/variables.scss";

.auth-layout {
  display: flex;
  padding-top: 2.5rem;
  padding-bottom: 2.5rem;
  justify-content: center;
  align-items: center;
  width: -webkit-fill-available;
}

.auth-image {
  width: 100%;
  align-items: center;
  display: flex;
  justify-content: center;
  img {
    max-width: 500px;
    height: fit-content;
  }
}

</style>
