// frameworks-comparison-angular/src/app/pages/update-profile/update-profile.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../../../services/userService';
import { FormControl, FormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { Store, select } from '@ngrx/store';

@Component({
  selector: 'app-update-profile',
  templateUrl: './update-profile.component.html',
  styleUrls: ['./update-profile.component.scss'],
})
export class UpdateProfileComponent {
  updateProfileForm: FormGroup = new FormGroup({
    userName: new FormControl(''),
    bio: new FormControl(''),
  });
  auth$: Observable<any>;
  user: any = null;
  file: File | null = null;
  fileURL: string | null = null;
  loading = false;

  constructor(
    private userService: UserService,
    private router: Router,
    private store: Store<{ auth: any }>
  ) {
    this.auth$ = this.store.pipe(select('auth'));
    this.auth$.subscribe((auth) => {
      this.user = auth.user;
      this.updateProfileForm.patchValue({
        userName: auth.user.userName,
        bio: auth.user.bio,
      });
      this.fileURL = auth.user.imageUrl;
    });
  }

  handleUpdateUser(): void {
    const userData = {
      userName: this.updateProfileForm.value.userName,
      bio: this.updateProfileForm.value.bio,
      file: this.file,
      email: this.user.email,
    };
    this.loading = true;

    this.userService.editUser(this.user.userId, userData).subscribe(
      () => {
        this.loading = false;
        this.router.navigate(['/profile', this.user.userId]);
      },
      () => {
        this.loading = false;
      }
    );
  }

  handleFileChange(event: any): void {
    const selectedFile = event.target.files?.[0];
    if (selectedFile) {
      this.file = selectedFile;
      this.fileURL = URL.createObjectURL(selectedFile);
    }
  }

  handleCancel(): void {
    this.router.navigate(['/profile', this.user.userId]);
  }

  handleButtonClick(): void {
    const fileInput = document.getElementById('fileInput');
    if (fileInput) {
      fileInput.click();
    }
  }
}

<div class="right-container">
    <div class="title-wrapper">
     <img src="../../../assets/icons/edit.svg" alt="edit">
      <h4>Edit Profile</h4>
    </div>
    <form [formGroup]="updateProfileForm" (ngSubmit)="handleUpdateUser()" class="update-profile-container">
      <div class="profile-photo">
        <img *ngIf="fileURL" [src]="fileURL" alt="profile" class="profile-img" />
        <img *ngIf="!fileURL && user.imageUrl" [src]="user.imageUrl" alt="profile" class="profile-img" />
        <img *ngIf="!fileURL && !user.imageUrl" src="assets/icons/profile-placeholder.svg" alt="profile" class="profile-img" />

        <div class="profile-input-file">
          <input id="fileInput" type="file" name="file" (change)="handleFileChange($event)" style="display: none" />
          <p class="custom-file-button" (click)="handleButtonClick()">Change profile photo</p>
        </div>
      </div>

      <app-input-text label="Username" placeholder="Username" formControlName="userName" ></app-input-text>
      <app-textarea label="Bio" placeholder="Bio" formControlName="bio"></app-textarea>
      <div class="buttons-section">
        <app-button variant="outlined" class="btn" (click)="handleCancel()">Cancel</app-button>
        <app-button class="btn" (click)="handleUpdateUser()">
          <ng-container *ngIf="loading; else updateProfileText">
            <div class="loader-wrapper">
              <app-loader></app-loader>
              Loading...
            </div>
          </ng-container>
          <ng-template #updateProfileText>Update Profile</ng-template>
        </app-button>
      </div>
    </form>
  </div>

// frameworks-comparison-react/src/pages/UpdateProfile/UpdateProfile.tsx
import React, { useState, ChangeEvent, useRef } from "react";
import "./UpdateProfile.scss";
import { useNavigate } from "react-router-dom";
import { useSelector } from "react-redux";
import { ReactComponent as UpdateIcon } from "../../assets/icons/edit.svg";
import InputText from "../../components/InputText/InputText";
import Button from "../../components/Button/Button";
import Loader from "../../components/Loader/Loader";
import Textarea from "../../components/Textarea/Textarea";
import UserService from "../../services/userService";

import ProfilePlaceholder from "../../assets/icons/profile-placeholder.svg";

const UpdateProfile = () => {
  const navigate = useNavigate();
  const { user } = useSelector((state: any) => state.auth);
  const [name, setName] = useState<string>("");
  const [username, setUsername] = useState<string>("");
  const [bio, setBio] = useState<string>("");
  const [file, setFile] = useState<any>(null);
  const [fileURL, setFileURL] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const fileInputRef: any = useRef(null);

  const handleNameChange = (e: ChangeEvent<HTMLInputElement>) => {
    setName(e.target.value);
  };

  const handleUsernameChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUsername(e.target.value);
  };

  const handleBioChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setBio(e.target.value);
  };

  const handleUpdateUser = () => {
    const userData = {
      name,
      username,
      email: user.email,
      bio,
      file,
    };

    UserService.editUser({ userId: user.userId, userData })
      .then(() => {
        setLoading(false);
        navigate(`/profile/${user.userId}`);
      })
      .catch(() => {
        setLoading(false);
      });
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setFileURL(URL.createObjectURL(selectedFile));
    }
  };

  const handleCancel = () => {
    navigate(-1);
  };

  const handleButtonClick = () => {
    if (fileInputRef.current) {
      fileInputRef.current.click();
    }
  };

  return (
    <div className="right-container">
      <div className="title-wrapper">
        <UpdateIcon />
        <h4>Edit Profile</h4>
      </div>
      <div className="update-profile-container">
        <div className="profile-photo">
          {fileURL ? (
            <img src={fileURL} alt="profile" className="profile-img" />
          ) : user.imageUrl ? (
            <img src={user.imageUrl} alt="profile" className="profile-img" />
          ) : (
            <img src={ProfilePlaceholder} alt="profile" className="profile-img" />
          )}

          <div className="profile-input-file">
            <input type="file" name="file" ref={fileInputRef} onChange={handleFileChange} style={{ display: "none" }} />
            <p className="custom-file-button" onClick={handleButtonClick}>
              Change profile photo
            </p>
          </div>
        </div>

        <InputText label="Name" placeholder="Name" onChange={handleNameChange} value={name} />
        <InputText label="Username" placeholder="Username" onChange={handleUsernameChange} value={username} />
        <Textarea label="Bio" onChange={handleBioChange} value={bio} />
        <div className="buttons-section">
          <Button variant="outlined" text="Cancel" onClick={handleCancel} />
          <Button onClick={handleUpdateUser} type="submit">
            {loading ? (
              <div className="loader-wrapper">
                <Loader />
                Loading...
              </div>
            ) : (
              "Update Profile"
            )}
          </Button>
        </div>
      </div>
    </div>
  );
};

export default UpdateProfile;
