// frameworks-comparison-react/src/pages/Login/Login.tsx
import { useState, ChangeEvent } from "react";
import "./Login.scss";
import Button from "../../components/button/Button";
import TextButton from "../../components/text-button/TextButton";
import InputText from "../../components/input-text/InputText";
import { useDispatch } from "react-redux";
import { Link, useNavigate } from "react-router-dom";
import { login } from "../../redux/actions/auth";
import Loader from "../../components/loader/Loader";

const Login = () => {
  let navigate = useNavigate();

  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [loading, setLoading] = useState(false);

  const dispatch: any = useDispatch();
  const handleEmailChange = (e: ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>) => {
    setPassword(e.target.value);
  };

  const handleLogin = (e: any) => {
    e.preventDefault();

    setLoading(true);

    dispatch(login(email, password))
      .then(() => {
        navigate("/home");
        setLoading(false);
      })
      .catch(() => {
        setLoading(false);
      });
  };

  return (
    <>
      <div className="auth-page">
        <div className="left-side">
          <h2 className="logo">PostShare</h2>
          <div className="auth-header">
            <h4>Log in to your account</h4>

            <p className="normal-md gray-500">Welcome back! Please enter your details</p>
          </div>
          <form onSubmit={handleLogin} className="auth-form">
            <div className="form-group">
              <InputText label="Email" placeholder="Email" onChange={handleEmailChange} value={email} />
            </div>
            <div className="form-group">
              <InputText type="password" label="Password" placeholder="Password" onChange={handlePasswordChange} value={password} />
            </div>

            <Button onClick={handleLogin} type="submit">
              {loading ? (
                <div className="loader-wrapper">
                  <Loader />
                  Loading...
                </div>
              ) : (
                "Log in"
              )}
            </Button>
          </form>
          <div className="signup-link">
            <span>Don’t have an account? </span>
            <Link to="/sign-up">
              <TextButton text="Sign Up" />
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;

// frameworks-comparison-angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
// import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent {
  loginForm: FormGroup;
  loading: boolean = false;

  constructor(
    private formBuilder: FormBuilder,
    // private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
    });
  }

  get f() {
    return this.loginForm.controls;
  }

  onSubmit() {
    if (this.loginForm.invalid) {
      return;
    }

    this.loading = true;

    // this.authService.login(this.loginForm.value.email, this.loginForm.value.password)
    //   .subscribe(
    //     () => {
    //       this.router.navigate(['/']);
    //     },
    //     () => {
    //       this.loading = false;
    //     }
    //   );
  }
}

<div class="auth-page">
  <div class="left-side">
    <h2 class="logo">PostShare</h2>
    <div class="auth-header">
      <h4>Log in to your account</h4>
      <p class="normal-md gray-500">Welcome back! Please enter your details</p>
    </div>
    <!-- <form
    [formGroup]="loginForm"
     (ngSubmit)="onSubmit()" class="auth-form"> -->
      <div class="form-group">
        <app-input-text label="Email" placeholder="Email" formControlName="email"></app-input-text>
      </div>
      <div class="form-group">
        <app-input-text label="Password" placeholder="Password" type="password" formControlName="password"></app-input-text>
      </div>
      <app-button type="submit">
        <ng-container *ngIf="loading; else elseBlock">
          <div class="loader-wrapper">
            <app-loader></app-loader>
            Loading...
          </div>
        </ng-container>
        <ng-template #elseBlock>
          Log in
        </ng-template>
      </app-button>
    <!-- </form> -->
    <div class="signup-link">
      <span>Don’t have an account? </span>
      <a routerLink="/sign-up" class="text-button">Sign Up</a>
    </div>
  </div>
</div>
