// frameworks-comparison-vue/src/components/InputText.vue
<script lang="ts">
export default {
  props: {
    label: String,
    placeholder: String,
    size: {
      type: String,
      default: "medium",
      validator: (value) => ["small", "medium", "large"].includes(value),
    },
    onChange: {
      type: Function as () => void,
      default: () => {},
    },
    value: String,
    type: {
      type: String,
      default: "text",
    },
  },
};
</script>

<template>
  <div :class="'input-container'">
    <label v-if="label" :class="['input-label', `input-label--${size}`]">{{ label }}</label>
    <input :type="type" :placeholder="placeholder" @input="onChange" :value="value" :class="['input-text', `input-text--${size}`]" />
  </div>
</template>

<style scoped lang="scss">
@import "../assets/scss/variables.scss";

.input-container {
  display: flex;
  flex-direction: column;
  .input-text {
    border: 1px solid $gray-200;
    color: $black;
    padding: 0 16px;
    outline: none;
  }

  .input-text::placeholder {
    color: $gray-400;
  }

  .input-text:hover,
  .input-text:active {
    border-color: $primary-500;
    border-width: 1px;
  }

  .input-text:focus {
    border-color: $primary-500;
    border-width: 2px;
    padding: 0 15px;
  }

  .input-text--small {
    height: 32px;
    border-radius: 4px;
  }

  .input-text--medium {
    height: 40px;
    border-radius: 4px;
  }

  .input-text--large {
    height: 48px;
    border-radius: 6px;
  }

  .input-label {
    color: $black;
    margin-bottom: 8px;
  }

  .input-label--small {
    font-size: 14px;
  }

  .input-label--medium {
    font-size: 16px;
  }

  .input-label--large {
    font-size: 18px;
  }
}
</style>

// frameworks-comparison-react/src/components/InputText/InputText.tsx
import React, { ChangeEvent } from "react";
import "./InputText.scss";

interface InputTextProps {
  label?: string;
  placeholder?: string;
  size?: "small" | "medium" | "large";
  onChange: (event: ChangeEvent<HTMLInputElement>) => void;
  value: string;
  type?: string;
}

const InputText = ({ label, placeholder, size = "medium", onChange, value, type = "text" }: InputTextProps) => {
  return (
    <div className="input-container">
      {label && <label className={["input-label", `input-label--${size}`].join(" ")}>{label}</label>}
      <input type={type} placeholder={placeholder} onChange={onChange} value={value} className={["input-text", `input-text--${size}`].join(" ")} />
    </div>
  );
};

export default InputText;
